# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-27 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
    ]
